# Generated by Django 5.0 on 2023-12-31 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='hey there this default text description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='john Doe (default)', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, default='media/1.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='this is default , title change in hi sprofiel', max_length=200, null=True),
        ),
    ]
