# Generated by Django 5.0 on 2024-01-01 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_profile_desc_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='--------------', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='-----', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImg',
            field=models.ImageField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='---------', max_length=200, null=True),
        ),
    ]
